[book]
authors = ["Herbert Wolverson"]
language = "en"
multilingual = false
src = "src"
title = "Introduction to Rust - From Go"

[rust]
edition = "2021"

[output.html.playground]
editable = true

[output.html]
default-theme = "light"